method: bayes
metric:
    goal: maximize
    name: dev/pp_acc
parameters:
    dontsave:
        value: true
    smaller:
        value: true
    num_hidden_layers:
        value: 12
    lr: #based on https://wandb.ai/sonsus/albert_paraphrase/runs/8w194kha?workspace=user-sonsus
        value: 0.0002
    alpha_pp:
        distribution: q_uniform
        max: 0.1
        min: 0.005
        q: 0.005
    warmups: #based on https://wandb.ai/sonsus/albert_paraphrase/runs/8w194kha?workspace=user-sonsus
        value: 1000
    numep:
        value: 100
    kfold_k:
        value: 0
    albert_scale:
        value: base # large-64 / base-128 on titanXp
    bsz:
        value: 512
    scheduler:
        value: linear
    masking:
        value: span # for searching
program: train_albert.py
command:
    - python
    - ${program}
    - ${args}
